[package]
name = "RustKeyLogger"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.52", features = ["Win32_UI_Input_KeyboardAndMouse"] }

[profile.release]
strip = false

